# This is a basic workflow to help you get started with Actions

name: merge-checks

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  sast:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # 4.2.2
      - name: semgrep-action
        uses: semgrep/semgrep-action@713efdd345f3035192eaa63f56867b88e63e4e5d #v1
  secrets:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    container:
      image: ghcr.io/gitleaks/gitleaks:latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # 4.2.2
      - name: GitLeaks
        run: |
          git config --global --add safe.directory /__w/black-hole/black-hole
          gitleaks detect --verbose
    
      