on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
    branches:
      - main      

name: Default CI Pipeline

jobs:    
  version:
    uses: innago-property-management/Oui-DELIVER/.github/workflows/semver.yml@main
    permissions:
      contents: read
  security:
    uses: ./.github/workflows/security.yml
    permissions:
      contents: read
  test:
    uses: ./.github/workflows/test.yml
    permissions: {}
  package-and-publish:
    uses: ./.github/workflows/package-and-publish.yml
    secrets: inherit
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    needs:
      - test
      - version
      - security
    with:
      version: ${{ needs.version.outputs.version }}
      imageName: ${{ toLower(github.event.repository.name) }}
