name: test.yml
on:
  workflow_call:
    
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    permissions: {}
    strategy:
      matrix:
        deno-version: ['2.x']
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # 4.2.2

      - name: Setup Deno ${{ matrix.deno-version }}
        uses: denoland/setup-deno@27e0043effb637fb8409496e05bd8472e4b87554
        with:
          deno-version: ${{ matrix.deno-version }}

      - name: Run tests and collect coverage
        run: deno test src/ --allow-read --allow-net --allow-env --coverage=coverage

      - name: Generate LCOV report
        run: deno coverage ./coverage --lcov --output=coverage.lcov

      - name: Add coverage summary to job summary
        if: always()
        run: |
          echo "### Code Coverage Summary" >> $GITHUB_STEP_SUMMARY
          npx lcov-summary coverage.lcov >> $GITHUB_STEP_SUMMARY

      - name: Upload coverage artifact
        if: always()
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: coverage-report-lcov
          path: coverage.lcov
